<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="Bharath" failures="1" tests="6" name="Test" time="9.119" errors="0" timestamp="2025-04-30T09:05:02 IST">
  <testcase classname="framework.tesng.concepts.AppCommons" name="TestCase3" time="3.021"/>
  <testcase classname="framework.tesng.concepts.AppCommons" name="TestCase3" time="3.015"/>
  <testcase classname="framework.tesng.concepts.AppCommons" name="TestCase1" time="0.006">
    <skipped/>
  </testcase> <!-- TestCase1 -->
  <testcase classname="framework.tesng.concepts.AppCommons" name="TestCase1" time="0.001">
    <skipped/>
  </testcase> <!-- TestCase1 -->
  <testcase classname="framework.tesng.concepts.AppCommons" name="TestCase1" time="0.001">
    <failure type="java.lang.AssertionError" message="Error in Test Case 1">
      <![CDATA[java.lang.AssertionError: Error in Test Case 1
at framework.tesng.concepts.AppCommons.TestCase1(AppCommons.java:10)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- TestCase1 -->
  <testcase classname="framework.tesng.concepts.AppCommons" name="TestCase4" time="3.015"/>
  <testcase classname="framework.tesng.concepts.AppCommons" name="TestCase2" time="0.0">
    <ignored/>
  </testcase> <!-- TestCase2 -->
</testsuite> <!-- Test -->
